### ISSUE TITLE
Error pulling images. "got response code 403 from Unsplash - Forbidden"

### ISSUE THREAD

**Issue by erikfurevik** [MehediH/Bulksplash#39] opened 2022-01-09 17:44 UTC
Hi, I downloaded node.js, installed bulksplash as instructed (npm install), but I get the following result (example input):

```
C:\Users\***>bulksplash
? 📂 Which directory do you want to save to? F:/
? 📸 Which images do you want to download? Random
? 🔍 What search term? nature
? 👀 How many images? 100
? ⭐️ Only featured images? Yes
? 🤔 What orientation? Landscape
? 🖼 Width? (Optional, blank for original size)
? 🖼 Height? (Optional, blank for original size)
? 🗂  Export the credits for the photos to a .json file?  No

🤖 Welcome to Bulksplash! (Powered by Unsplash.com)

🔰 Downloading 100 featured "nature" images from:
🚨 Something went wrong, got response code 403 from Unsplash - Forbidden
🚨 Something went wrong, got response code 403 from Unsplash - Forbidden
🚨 Something went wrong, got response code 403 from Unsplash - Forbidden
🚨 Something went wrong, got response code 403 from Unsplash - Forbidden

C:\Users\****>
```

**Comment by JanPokorny** [comment] 2022-01-17 13:40
The real problem is that the library won't let you enter your own API key, it instead hardcodes a few API keys which is a big no-no.

https://github.com/MehediH/Bulksplash/blob/master/index.js#L143-L144

**Comment by matthewmayer** [comment] 2022-01-18 09:37
i made a fork which prompts for API key as first question instead of hardcoding:
https://github.com/matthewmayer/Bulksplash

**Comment by MehediH** [comment] 2022-01-18 09:39
> The real problem is that the library won't let you enter your own API key, it instead hardcodes a few API keys which is a big no-no.
> 
> https://github.com/MehediH/Bulksplash/blob/master/index.js#L143-L144

The main reason behind this was to make it easy for people to just install the library and download the images, I know it's a big no-no to hardcode API keys, but by needing users to enter their own API key, it prevents quick use of the library

**Comment by matthewmayer** [comment] 2022-01-18 09:40
i think unsplash may have blocked those api keys for overuse though :(

**Comment by MehediH** [comment] 2022-01-18 09:41
> i made a fork which prompts for API key as first question instead of hardcoding: https://github.com/matthewmayer/Bulksplash

Nice! If you have the time, please open a PR for this! Also, I'd probably API key prompt optional and fallback to the hardcoded API keys if the user doesn't have one.

**Comment by MehediH** [comment] 2022-01-18 09:44
> i think unsplash may have blocked those api keys for overuse though :(

Ahh, possibly, the problem is that if a new user was to use this library, they'd have to go through the process of requesting a new one, and then apply for production access:

![image](https://user-images.githubusercontent.com/10274434/149912028-2bd7f568-e726-495b-a945-5aae10c7d3dd.png)

Otherwise they are limited to 50 requests an hour, which is quite limiting. And applying for production access takes some time :(

**Comment by matthewmayer** [comment] 2022-01-18 09:45
added a PR, sorry i dont have time to do a lot of polish on this yet. i think it won't work with the CLI parameters only the prompts at the moment.

**Comment by MehediH** [comment] 2022-01-18 10:03
thanks @matthewmayer, I have merged the PR and added some comments to the README. I will find some time to update the API key option so that we can store it locally in the user's device somewhere and can be reused without needing to ask them everytime.

**Comment by matthewmayer** [comment] 2022-01-18 10:04
Yeah that would be nice, it could write to like a .bulksplash file in the current folder?

**Closed as completed** 2022-01-18 10:03 UTC

**Comment by MehediH** [comment] 2022-01-18 10:05
Yes, and in that case we can just store their entire config as well -- and on use, prompt the user to ask if they just want to use their usual config

**Comment by matthewmayer** [comment] 2022-01-18 11:01
maybe store the last entered data, and then default to that for each question? then if i want to do a similar request i can just hit ENTER repeatedly, but i can override as needed (e.g. i downloaded 10 dog photos, now i want 10 cat photos)?
